//category//
export const GET_CATEGORY="GET_CATEGORY"
export const LOADING_CATEGORY="LOADING_CATEGORY"
export const ERROR_CATEGORY="ERROR_CATEGORY"
export const POST_CATEGORY="POST_CATEGORY"
export const DELETE_CATEGORY="DELETE_CATEGORY"
export const UPDATE_CATEGORY="UPDATE_CATEGORY"

//Product//

export const GET_PRODUCT="GET_PRODUCT"
export const LOADING_PRODUCT="LOADING_PRODUCT"
export const ERROR_PRODUCT="ERROR_PRODUCT"
export const POST_PRODUCT="POST_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"